void setup() {
  pinMode(0, OUTPUT);
  pinMode(1, OUTPUT);
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  pinMode(11, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
  pinMode(14, OUTPUT);
  pinMode(15, OUTPUT);
  pinMode(16, OUTPUT);
  pinMode(17, OUTPUT);
  pinMode(18, OUTPUT);
  pinMode(19, OUTPUT);
  pinMode(27, OUTPUT);

  Serial.begin(115200);
  while(!Serial){
    yield();
  };
  Serial.println("Beginning GPIO test at top left, moving down, then across and back up.\n");
}

void loop() {
  digitalWrite(3, HIGH);
  delay(100);
  digitalWrite(3, LOW);
  delay(50);
  digitalWrite(4, HIGH);
  delay(100);
  digitalWrite(4, LOW);
  delay(50);
  digitalWrite(5, HIGH);
  delay(100);
  digitalWrite(5, LOW);
  delay(50);
  digitalWrite(6, HIGH);
  delay(100);
  digitalWrite(6, LOW);
  delay(50);
  digitalWrite(9, HIGH);
  delay(100);
  digitalWrite(9, LOW);
  delay(50);
  digitalWrite(10, HIGH);
  delay(100);
  digitalWrite(10, LOW);
  delay(50);
  digitalWrite(11, HIGH);
  delay(100);
  digitalWrite(11, LOW);
  delay(50);
  digitalWrite(12, HIGH);
  delay(100);
  digitalWrite(12, LOW);
  delay(50);
  digitalWrite(13, HIGH);
  delay(100);
  digitalWrite(13, LOW);
  delay(50);
  digitalWrite(14, HIGH);
  delay(100);
  digitalWrite(14, LOW);
  delay(50);
  digitalWrite(15, HIGH);
  delay(100);
  digitalWrite(15, LOW);
  delay(50);
  digitalWrite(16, HIGH);
  delay(100);
  digitalWrite(16, LOW);
  delay(50);
  digitalWrite(17, HIGH);
  delay(100);
  digitalWrite(17, LOW);
  delay(50);
  digitalWrite(18, HIGH);
  delay(100);
  digitalWrite(18, LOW);
  delay(50);
  digitalWrite(19, HIGH);
  delay(100);
  digitalWrite(19, LOW);
  delay(50);
  digitalWrite(27, HIGH);
  delay(100);
  digitalWrite(27, LOW);
  delay(50);
  digitalWrite(7, HIGH);
  delay(100);
  digitalWrite(7, LOW);
  delay(50);
  digitalWrite(8, HIGH);
  delay(100);
  digitalWrite(8, LOW);
  delay(50);
  digitalWrite(0, HIGH);
  delay(100);
  digitalWrite(0, LOW);
  delay(50);
  digitalWrite(1, HIGH);
  delay(100);
  digitalWrite(1, LOW);
  delay(50);
  digitalWrite(2, HIGH);
  delay(100);
  digitalWrite(2, LOW);
  delay(50);
}
